#!/usr/bin/env bash

# usage: uterine-simulation <dim>
# Runs the chaste simulation, renames the log file and annotates data

echo ""
echo ">>>>>>>"
echo "Running Uterine Simulation"
echo "<<<<<<<"
echo ""

# Check arguments
if [[ $# -ne 1 ]]; then
	echo "Error: missing simulation dimension"
	echo "usage: uterine-simulation <dim>"
	exit
fi

# Move to the app directory and run the simulation
cd ${CHASTE_BUILD_DIR}/projects/uterine-modelling

# Get the config file based on dimension
if [[ $1 -eq 2 ]]; then
	CONFIG=${CHASTE_MODELLING_CONFIG_DIR}general/2d_params.toml
elif [[ $1 -eq 3 ]]; then
	CONFIG=${CHASTE_MODELLING_CONFIG_DIR}general/3d_params.toml
fi

echo ""
echo "Using "${CONFIG}" file..."
#echo ""

# Get the name details
CELL_TYPE=$(grep "cell_type =" $CONFIG | cut -d '"' -f 2)
SAVE_DIR=$(grep "save_dir =" $CONFIG | cut -d '"' -f 2)
STIMULUS=$(grep "stimulus_type =" $CONFIG | cut -d '"' -f 2)
BASE_DIR=${CHASTE_TEST_OUTPUT}/${CELL_TYPE}/${SAVE_DIR}
#BASE DIR now with stimulus appended
#BASE_DIR=${CHASTE_TEST_OUTPUT}/${CELL_TYPE}/${SAVE_DIR}/${STIMULUS}

echo "BASE directory:"${BASE_DIR}$"..."
echo ""

./apps/main $1

# Move to the stimulus folder
cd ${BASE_DIR}

#create log folder if non existent
if [ ! -d "${BASE_DIR}/log" ]; then
	mkdir ${BASE_DIR}/log
fi

# Move to the log folder to rename the log file
cd ${BASE_DIR}/log
NB_FILES=$(printf "%0.3d" $(ls | wc -l))
mv log.log "simulation_${NB_FILES}.log"

#cd back to base_dir
cd ${BASE_DIR}

#create BASE_DIR + stimulus folder if non existent
if [ ! -d "${BASE_DIR}" ]; then
	echo "making stimulus directory..."
	mkdir ${BASE_DIR}/${STIMULUS}
fi

echo ""
echo "Moving results to directory " ${BASE_DIR}"/"${STIMULUS}"/results"
echo ""

#test 
#cd "${BASE_DIR}/${STIMULUS}/results"
# Create results folder if it does not exist
if [ ! -d "${BASE_DIR}/${STIMULUS}/results" ]; then
	echo "making results directory..."
	mkdir ${BASE_DIR}/${STIMULUS}/results
fi

#change to stimulus directory
cd ${BASE_DIR}/${STIMULUS}
#CUR_PWD=pwd
echo "current pwd: "${PWD}


# Annotate the data for viewing
SIM_RES_NAME="simulation_${NB_FILES}.vtu"

echo ""
echo "Saving results to filename " ${SIM_RES_NAME}
echo ""

#below runs into issues with Chaste deleting results directory
#python3 ${CHASTE_SOURCE_DIR}/python/utils/AddVtuTimeAnnotations.py vtk_output/results.vtu ${BASE_DIR}/${STIMULUS}/results/${SIM_RES_NAME}
#below instead assumes output into default chasteoutput: CHASTE_TEST_OUTPUT/ChasteResults
python3 ${CHASTE_SOURCE_DIR}/python/utils/AddVtuTimeAnnotations.py ${CHASTE_TEST_OUTPUT}/ChasteResults/vtk_output/results.vtu ${BASE_DIR}/${STIMULUS}/results/${SIM_RES_NAME}