# General parameters
save_dir = "monodomain_3d/diestrus"
mesh_name = "uterus_scaffold_2"
mesh_dir = "/mesh/uterus/scaffolds/"  # Must end with /
stimulus_type = "region"

# Stimulus parameters
x_stim_start = -500.1
x_stim_end = 500.1
y_stim_start = -500.0
y_stim_end = 500.0
z_stim_start = 30.0
z_stim_end = 45.0

# Time paramters in millisec
sim_duration = 15.0e3
ode_timestep = 1.0
pde_timestep = 1.0
print_timestep = 2.0

# Cell parameters
cell_type = "Roesler"
estrus = "diestrus"
