# General parameters
save_dir = "monodomain_3d"
mesh_name = "rat_uterus_idealised_10mm_4704_elem"
mesh_dir = "/mesh/rat_uterus/"
stimulus_type = "simple"

# Stimulus parameters
x_stim_start = -1.1
x_stim_end = 1.1
y_stim_start = -2.0
y_stim_end = 2.0
z_stim_start = -0.1
z_stim_end = 1.0

# Time paramters in millisec
sim_duration = 10000.0
ode_timestep = 0.1
pde_timestep = 0.1
print_timestep = 1.0

# Cell parameters
cell_type = "Means"
