# Cell properties
capacitance = 5300.0 # uF/cm2
conductivities_2d = [0.0, 0.05] #x, y 
conductivities_3d = [0.0, 0.05, 0.01] #x, y, z

# Stimulus
magnitude = 0.0 # uA/cm2
period = 0.1 # ms
duration = 0.5 # ms
start_time = 5.0 # ms

cell_id = 1
