# Cell properties
capacitance = 1.3 # uF/cm2
conductivities_2d = [0.0, 0.0] 
conductivities_3d = [0.1, 0.1, 0.1] 
ortho_conductivities = [0.8, 0.08, 0.08]

# Stimulus
magnitude = -3.1e3
period = 71.0e3 # ms
duration = 10.0e3 # ms
start_time = 1.0e3 # ms
region_p = [0.5, 0.4, 0.1]  # ova, cen, cvx
cell_id = 4

# Cell parameters
[parameters]
   gna = 0.0625 # 0.0625
   gkv43 = 2.2 # 2.04
   gkca = 2.4 # 2.4
   gcal = 0.6  # 0.6 
   gcat = 0.058 # 0.058
   E2 = 49.0 # 49.0
   P4 = 25.0 # 25.0


