# Cell properties
capacitance = 1.3  # uF/cm2
conductivities_2d = [0.2, 0.2] 
conductivities_3d = [1.1, 1.1, 1.1] 
ortho_conductivities = [0.55, 0.055, 0.055]

# Stimulus
magnitude = 0.0
period = 56.5e3  # ms
duration = 10.0e3  # ms
start_time = 1.0e3  # ms
region_p = [0.92, 0.08, 0.0]  # ova, cen, cvx
cell_id = 5

# Cell parameters
[parameters]
   gna = 0.0625  # 0.0625
   gkv43 = 2.65  # 2.65
   gkca = 2.4  # 2.4
   gcal = 0.8  # 0.6 
   gcat = 0.058  # 0.058
   g_p = 0.050 # 0.013
   E2 = 40.0  # 40.0
   P4 = 14.0  # 14.0
