# Cell properties
capacitance = 1.3 # uF/cm2
conductivities_2d = [0.2, 0.2] 
conductivities_3d = [0.4, 0.4, 0.4] 
ortho_conductivities = [1.7, 0.17, 0.17]

# Stimulus
magnitude = -1.93e3
period = 45.0e3 # ms
duration = 10.0e3 # ms
start_time = 1.0e3 # ms
region_p = [0.5, 0.5, 0.0]  # ova, cen, cvx

cell_id = 4

# Cell parameters
[parameters]
   gna = 0.0625 # 0.0625
   gkv43 = 1.2 # 1.3
   gkca = 2.4 # 2.4
   gcal = 0.6  # 0.6 
   gcat = 0.058 # 0.058
   E2 = 90.0 # 90
   P4 = 10.0 # 10
