# Cell properties
capacitance = 1.0 # uF/cm2
conductivities_2d = [0.00, 0.00] #x, y
conductivities_3d = [0.1, 0.1, 0.1] #x, y, z

# Stimulus
magnitude = -0.55e3 # uA/cm2
period = 45.0e3 # ms
duration = 10.0e3 # ms
start_time = 1.0e3 # ms

cell_id = 6

# Cell parameters
[parameters]
   gna = 0.0895 # 0.0895 range 0.028 - 0.125
   gkv43 = 0.7 # 0.7 range 0.52 - 0.85
   gcal = 0.6 # 0.6
   gcat = 0.058 # 0.058

# Passive cell parameters
[passive]
   type = "gaussian"  # linear or gaussian
   g_p = 0.025
   slope = 0.05
   centre = 5.0
   amplitude = 0.1
