# Cell properties
capacitance = 1.0 # uF/cm2
conductivities_2d = [0.00, 0.00] #x, y
conductivities_3d = [0.4, 0.4, 0.4] #x, y, z

# Stimulus
#magnitude = -0.55e3 # uA/cm2
magnitude = 0.0
period = 45.0e3 # ms
duration = 10.0e3 # ms
start_time = 1.0e3 # ms

cell_id = 6

# tissue conductivity modifers
[tissuemod]
   conductivity_mod_type = "gaussian" #none or linear or gaussian
   conduct_mod_center = 0.0   #centre
   conduct_mod_steep = 0.3    #steepness
   conduct_mod_min = 0.5    #baseline 
   conduct_mod_amplitude = 0.5 #amplitude

# Cell parameters
[parameters]
   gna = 0.0895 # 0.0895 range 0.028 - 0.125
   gkv43 = 0.7 # 0.7 range 0.52 - 0.85
   gcal = 0.6 # 0.6
   gcat = 0.058 # 0.058

# Passive cell parameters
[passive]
   type = "gaussian"  # linear or gaussian
   #g_p = 0.025
   g_p = 0.017
   #g_p = 0.0
   #slope = 0.05
   slope = 0.3 #steep for gaussian
   centre = 0.0
   amplitude = 0.5
   min = 0.5
   #below for random noise (normally-dist) addition to g_p
   #mean = 1.0
   #stddev = 0.01
   #below for exponengial distribution
   #mean = 0.85 # = 1/lambda
   mean = 1.0
   #below for pareto; mean for scaling, stddev for shaping
   #mean here gives scaling 
   #mean = 4.5
   #stddev = 0.45
