# Cell properties
capacitance = 1.0 # uF/cm2
conductivities_2d = [0.00, 0.00] #x, y
conductivities_3d = [100.0, 100.0, 100.0] #x, y, z

# Stimulus
magnitude = -0.50e3 # uA/cm2
period = 0.1 # ms
duration = 2000.0 # ms
start_time = 2000.0 # ms

cell_id = 2

# Cell parameters
[parameters]
   gna = 0.125 # 0.0895 range 0.028 - 0.125
   beta = 0.0158 # 0.015
   gkv43 = 0.52 # 0.7 range 0.52 - 0.85
   gcal = 0.7 # 0.6
   gcat = 0.058 # 0.058
