#!/usr/bin/env bash

if [[ $# -ne 2 ]]; then
	echo "usage: multi-simulation <dim> <nb-runs>"
	exit
fi

DIM=$1
NB_RUNS=$2
I=0
NAME=$(uname -n)

if [[ $NAME == "hpc"? ]]; then
	source ~/Chaste/scripts/chaste-env
fi

while [[ $I -ne $NB_RUNS ]];
do
	# Run simulation
	echo "Running simulation $I" >&2
	${CHASTE_DIR}/scripts/uterine-simulation ${DIM} > ${CHASTE_DIR}/tmp.log

	# Save simulation times
	$(echo Simulation $I >> ${CHASTE_DIR}/times.log)
	$(cat tmp.log | grep Total >> ${CHASTE_DIR}/times.log)
	$(cat tmp.log | grep seconds >> ${CHASTE_DIR}/times.log)

	# Increase counter
	I=$((${I} + 1))
done

rm tmp.log
