#!/usr/bin/env bash
#
# usage: parameter-sweep <dim> <param> <start-val> <end-val> <step>
# Runs the parameter-sweep.py script

if [[ -z ${CHASTE_PROJECTS_DIR} ]]; then
	SCRIPT_PATH=${APPTAINERENV_CHASTE_PROJECTS_DIR}
else
	SCRIPT_PATH=${CHASTE_PROJECTS_DIR}
fi

python3 ${SCRIPT_PATH}/uterus-modelling/python/parameter-sweep.py $@
