[left]  # Left horn
  # x and y set to include entire horn for every region
  x_start=-526.0
  x_end=-282.0
  y_start=-408.0
  y_end=-258.0

[left.cervical]  # Cervical end
  z_start=87.0
  z_end=137.0

[left.centre]  # Centre of horn
  z_start=271.0
  z_end=321.0

[left.ovaries]  # Ovarian end
  z_start=455.0
  z_end=505.0

[right]  # Right horn
  # x and y set to include entire horn for every region
  x_start=-282.0
  x_end=-24.0
  y_start=-425.0
  y_end=-255.0

[right.cervical]  # Cervical end
  z_start=87.0
  z_end=137.0

[right.centre]  # Centre of horn
  z_start=287.0
  z_end=337.0

[right.ovaries]  # Ovarian end
  z_start=488.0
  z_end=538.0


