[left]  # Left horn
  # x and y set to include entire horn for every region
  x_start=-502.0
  x_end=-300.0
  y_start=-360.0
  y_end=-187.0

[left.cervical]  # Cervical end
  z_start=100.0
  z_end=150.0

[left.centre]  # Centre of horn
  z_start=282.0
  z_end=332.0

[left.ovaries]  # Ovarian end
  z_start=465.0
  z_end=515.0

[right]  # Right horn
  # x and y set to include entire horn for every region
  x_start=-300.0
  x_end=-168.0
  y_start=-356.0
  y_end=-187.0

[right.cervical]  # Cervical end
  z_start=105.0
  z_end=150.0

[right.centre]  # Centre of horn
  z_start=282.0
  z_end=332.0

[right.ovaries]  # Ovarian end
  z_start=465.0
  z_end=515.0


