[left]  # Left horn
  # x and y set to include entire horn for every region
  x_start=-562.0
  x_end=-372.0
  y_start=-412.0
  y_end=-259.0

[left.cervical]  # Cervical end
  z_start=102.0
  z_end=152.0

[left.centre]  # Centre of horn
  z_start=271.0
  z_end=321.0

[left.ovaries]  # Ovarian end
  z_start=440.0
  z_end=490.0

[right]  # Right horn
  # x and y set to include entire horn for every region
  x_start=-372.0
  x_end=-108.0
  y_start=-395.0
  y_end=-262.0

[right.cervical]  # Cervical end
  z_start=102.0
  z_end=152.0

[right.centre]  # Centre of horn
  z_start=271.0
  z_end=321.0

[right.ovaries]  # Ovarian end
  z_start=440.0
  z_end=490.0


